### ISSUE TITLE
tiddle & omniauth

### ISSUE THREAD

**Issue by akshah123** [adamniedzielski/tiddle#12]
Hello,

I am curious if I can omniauth features of devise while using tiddle. 

Would this work without having to do anything custom?

Thanks.

**Comment by adamniedzielski** [comment]
I've never tried combining Tiddle with omniauth. Theoretically, this should work as these are two independent authentication methods and I cannot see any obvious obstacles on your way.

If you manage to do it please share your experience.

**Comment by adamniedzielski** [comment]
I'm closing this one due to inactivity.

**Comment by AndrewDPalmer** [comment]
Interesting timing. This is actually what I am trying to do Adam! I'll be sure to update if I get it to work

**Comment by javvarcar** [comment]
@AndrewDPalmer , did you tried it with omniauth?
