### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by dflourusso** [adamniedzielski/tiddle#14]
After add `gem 'tiddle'` and `bundle`, when i restart the server, i got the follow error:
`.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.5.2/lib/devise/strategies/base.rb:4:in '<module:Strategies>': uninitialized constant Warden (NameError)`

**Comment by adamniedzielski** [comment]
What was the reason of this error? Can you share your solution?

**Comment by dflourusso** [comment]
I have this problem in one of my projects, then i created a new one to test, and in the new one it works fine.
I think its a conflict with gems versions for this specific project and it wasn't solved yet.
Thanks.

**Comment by johnernaut** [comment]
For anyone else that hits this, this happened to me when I had `gem 'tiddle'` **above** `gem 'devise'` in my Gemfile.  Load ordering issue.
