### ISSUE TITLE
Use in Angularjs

### ISSUE THREAD

**Issue by dflourusso** [adamniedzielski/tiddle#20]
To make the use more easy, i created a *Angularjs* plugin to use with *tiddle*.
Follows the link: [ng-tiddle](https://github.com/dflourusso/ng-tiddle) :)

**Comment by adamniedzielski** [comment]
That's really cool @dflourusso! It certainly reduces the amount of custom code required to integrate Tiddle in AngularJS.

I can only suggest translating the README to English for a wider adoption.

**Comment by dflourusso** [comment]
Thanks @adamniedzielski.
Now the README was translated.
