### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by adamniedzielski** [adamniedzielski/tiddle#22]

**Comment by alejandrogutierrez** [comment]
I'm using it with a rails 5.beta2 API, devise 4.0.0.rc1 and latest dependencies versions and everything it's ok. [https://github.com/alejandrogutierrez/tiddle/commits/rails-5](https://github.com/alejandrogutierrez/tiddle/commits/rails-5)

I think I can send a PR changing dependecies to:
```ruby
spec.add_dependency "devise", ">= 3.4.1"
spec.add_dependency "activerecord", ">= 4.2.0"
spec.add_development_dependency "rails", ">= 4.2.1"
```

**Comment by adamniedzielski** [comment]
@alejandrogutierrez Thanks for your input! Do you know what is the first version of Devise which supports Rails 5? Is it 4.x line?

**Comment by alejandrogutierrez** [comment]
4.x went well in my rails 5 API. :+1:
