### ISSUE TITLE
devise, ">= 4.0.0.rc1", "< 4.1"

### ISSUE THREAD

**Issue by alejandrodevs** [adamniedzielski/tiddle#26]
Because there is a new devise version (4.1.1) I think we need to upgrade dependencies to:
```ruby
spec.add_dependency "devise", ">= 4.0.0.rc1", "< 5.0.0"
```

What do you think? On another issue, are you planning to release other version?

**Comment by adamniedzielski** [comment]
Can you confirm that Tiddle works with 4.1.x version of Devise? You can check out the code, change gemspec, ensure that it uses 4.1.1 and run the tests.

I'm not sure about changing the maximum version to "< 5.0.0" - "< 4.2" would be probably saffer. What do you think?

At the beginning it wanted to wait for Rails 5.0.0 (not beta, not RC) before releasing Tiddle 0.7 with Rails 5 support. It's taking longer than I originally expected, but I believe that Rails team is pretty close.
