### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by adamniedzielski** [adamniedzielski/tiddle#28]
This gem has over a year and I consider it to be pretty stable at this point, so I would like to release version 1.0. Please share your feedback if you are using Tiddle in production.

**Comment by alejandrodevs** [comment]
Ey Adam!
Yes, I'm using it in production and everything is going pretty well.
Version 1.0 👍

**Comment by adamniedzielski** [comment]
🎉 🎉 🎉
