### ISSUE TITLE
Error after installed Tiddle

### ISSUE THREAD

**Issue by cardotrejos** [adamniedzielski/tiddle#31]
I get this error after installing Tiddle gem, I try everything but it persist...

`.rvm/gems/ruby-2.3.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:89:in`rescue in block (2 levels) in require': There was an error while trying to load the gem 'tiddle'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant Warden
Backtrace for gem load error is:
/home/cardotrejos/.rvm/gems/ruby-2.3.0/gems/devise-3.5.10/lib/devise/strategies/base.rb:4:in `<module:Strategies>'
/home/cardotrejos/.rvm/gems/ruby-2.3.0/gems/devise-3.5.10/lib/devise/strategies/base.rb:2:in`module:Devise'
/home/cardotrejos/.rvm/gems/ruby-2.3.0/gems/devise-3.5.10/lib/devise/strategies/base.rb:1:in `<top (required)>'....`

**Comment by adamniedzielski** [comment]
@cardotrejos I can only try to guess what causes this issue, because at this point I don't really know. Do you have `devise` gem listed in your Gemfile? If yes, is it before or after `tiddle`?

**Comment by adamniedzielski** [comment]
I'm closing this one due to the lack of response. Feel free to reopen if you still have this issue and can answer my question.

**Comment by bigfootspartan** [comment]
Just wanted to note I ran into the same problem. The issue was that I placed tiddle at the top of my gemfile. @adamniedzielski recommendation fixed it. Just incase anyone else runs into this.
