### ISSUE TITLE
Support devise > 4.3.X

### ISSUE THREAD

**Issue by alejandrodevs** [adamniedzielski/tiddle#33]
Hi Adam!

We need to add support for new devise version (4.3.0).
devise < 5 may works!

Greetings!

**Comment by alejandrodevs** [comment]
Or maybe without top limit:
devise, '>= 4.0.0'

**Comment by adamniedzielski** [comment]
@alejandrodevs Thanks for the heads-up. I released Tiddle 1.0.1 that allows Devise 4.3.0. I prefer to update these minor versions manually (4.2 -> 4.3) just to make sure that Tiddle still works.
