### ISSUE TITLE
Devise 4.4

### ISSUE THREAD

**Issue by piribes** [adamniedzielski/tiddle#38]
I can’t use tiddle 1.0.2 with devise 4.4

Bundler could not find compatible versions for gem “devise”:
  In Gemfile:
    devise (~> 4.4)
​
    tiddle (>= 1.0.2, ~> 1.0) was resolved to 1.0.2, which depends on
      devise (< 4.4, >= 4.0.0.rc1)

**Comment by adamniedzielski** [comment]
Hey @piribes 👋. Thanks for reporting this! Feel free to open a PR that bumps allowed version of Devise to `< 4.5`. If the build is green I can merge it.

**Comment by adamniedzielski** [comment]
Solved by #40

**Comment by wbreeze** [comment]
I'm trying-out Tiddle from edge, `gem 'tiddle', github: 'adamniedzielski/tiddle'` because, so far as I can tell, latest released gem doesn't have this change.

**Comment by tomca32** [comment]
Any chance for a release any time soon?
