### ISSUE TITLE
Removing or lowering required Ruby

### ISSUE THREAD

**Issue by krevels** [adamniedzielski/tiddle#4]
I'd like to try out Tiddle with a project running a previous Ruby (2.1.1) which I'm not able to update.  However, currently the gemspec specifies `~> 2.2.0`.  Is there any specific functionality in Tiddle that requires a Ruby that recent?  

Peeking through the code, I didn't find any, but I could be wrong.

**Comment by adamniedzielski** [comment]
I added Ruby 2.1.6 to be tested on Travis and it works, so I lowered required Ruby version.

I specified 2.2.0 because this was the only version which I tested Tiddle against. I didn't want to mislead anybody with promises of support about which I'm not sure.

**Comment by krevels** [comment]
I understand.  My initial thought was that since Tiddle was so minimal (in a good way!) that you could probably let your hard dependencies (devise, activerecord) specify that minimum version for you.  However, I've never tried to maintain a gem before, so I have no idea if this is a good practice.

Thanks for the update!
