### ISSUE TITLE
Soft purge setting `revoked_at` instead of destroying auth tokens?

### ISSUE THREAD

**Issue by edwinthinks** [adamniedzielski/tiddle#49]
I noticed that in the `purge_old_tokens` method that a `destroy_all` operation is used. My use case requires that I keep all my authorization tokens granted.

What do you think about setting a `revoked_at` timestamp instead of deleting the records?

**Comment by djkotowski** [comment]
@edwinthinks This is essentially what [paranoia](https://github.com/rubysherpas/paranoia) does.  You could add paranoia to your authentication token model to prevent them from being lost.

**Comment by edwinthinks** [comment]
@djkotowski good point! I didn't think to utilize paranoia in conjunction with this gem. That works, I'll close this ticket unless it makes sense to add the option soft delete without paranoia or some form of documentation :).
