### ISSUE TITLE
Add support for jruby

### ISSUE THREAD

**Issue by ninkibah** [adamniedzielski/tiddle#5]
I'll implement this myself, and send you a pull request when I'm done.

**Comment by adamniedzielski** [comment]
That's great, thank you!

**Comment by ninkibah** [comment]
@adamniedzielski, I have changed the requirements to be the same as devise 3.4.1, as that seems the most sensible thing to do. This means, I had to change the few lines of code you had that relied on ruby 2.1.

I use RVM to manage my gems and ruby versions, but I didn't add a .rvmrc. Let me know if I should add it to the project.

Tests all pass running under jruby 1.7.20. But, how do they work? The test rails app doesn't have a database.yml. I created a database.yml for postgresql, but, it doesn't seem to use the database while running the tests.

Finally, once I get tiddle integrated in my main project, and it is all working, I'll send you a push request. For now, you can look at my fork here.

**Comment by adamniedzielski** [comment]
I took a look at your fork. Can you tell me which version of MRI Ruby is jruby 1.7.20 compatible with? I don't want to support Ruby 1.9.3 - it doesn't even receive any security fixes now.

I also use RVM, but I don't think that committing ```.rvmrc``` or ```.ruby-version``` file is a good idea. ```.ruby-version``` is even added to ```.gitignore``` - https://github.com/adamniedzielski/tiddle/blob/022ef693d95998f7e2c80f4015eea6a74eac437a/.gitignore#L16

Database URL is hardcoded here: https://github.com/adamniedzielski/tiddle/blob/022ef693d95998f7e2c80f4015eea6a74eac437a/spec/spec_helper.rb#L13 Why do you want to use different database than sqlite?

Can you add Ruby versions for which you introduce support to ```.travis.yml```?

Thanks for your time! :)

**Comment by ninkibah** [comment]
Sadly, jruby 1.7 does not support MRI 2.x. They plan to support 2.2.x when jruby 9000 comes out.

Woops, I seem to actually have done the right thing, and use sqllite via the ARJDBC adapter.

I too would like to take advantage of all the new MRI 2.x features. Maybe in another 6 months, it will be possible.

**Comment by adamniedzielski** [comment]
So, jruby 1.7 is the latest stable version of jruby and it's compatible with Ruby 1.9.3 - do I understand it correctly? If so, feel free to make changes to support it.

**Comment by ninkibah** [comment]
Yes, this is correct. Sadly the current stable version of jruby, 1.7.20, only supports Ruby 1.9.3.

I'll remove the database.yml file, but I will leave the Gemfile with it's changes for the database adapters.

Pull request should be winging its way to you later today.

**Comment by adamniedzielski** [comment]
Hi @ninkibah ! Any progress on this? Are you still interested in adding support for jruby?

**Comment by adamniedzielski** [comment]
I'm closing this as outdated.
