### ISSUE TITLE
Multiple types of Users

### ISSUE THREAD

**Issue by Tiltorito** [adamniedzielski/tiddle#55]
Hi,

Is it possible to have the same table for AuthTokens for multiple types of users?

**Comment by adamniedzielski** [comment]
I don't see a particular reason why it won't be possible, but I also haven't tried that specific scenario. The only requirement is that each of your models should have `authentication_tokens` association. I guess that if you use polymorphic associations then it should be possible to have one table 😄That said, I'd just create one table per model as it's simpler.
