### ISSUE TITLE
Timeout and expiration for token

### ISSUE THREAD

**Issue by Hex-iang** [adamniedzielski/tiddle#8]
Hello,

Thanks for you sharing this authentication token tool. I have some question regards to the expiration timeout for the authentication tokens in database. Is there a place to set up the timeout value? How does it cooperate with Devise remember?

**Comment by adamniedzielski** [comment]
Hi! Currently there is no built-in way to setup expiration timeout. It can be easily implemented inside your application - create a Rake task which deletes tokens based on ```last_used_at``` or ```created_at``` fields and invoke it from a cron job.

We have ```Tiddle.purge_old_tokens``` method which has a slightly different purpose. It keeps number of tokens under 20 for each user in order not to litter database with unused tokens. Take a look here: https://github.com/adamniedzielski/tiddle/blob/022ef693d95998f7e2c80f4015eea6a74eac437a/lib/tiddle/token_issuer.rb#L32 and here: http://adamniedzielski.github.io/blog/2015/04/04/token-authentication-with-tiddle/ -> Deleting old tokens. The code for token expiration should be quite similar.

Tiddle does not work with Devise rememberable. Tiddle is intended to be used in cookie-less applications and token should be sent with each request.

I hope that my answer helps you :) If you have further questions - ask!
