### ISSUE TITLE
Devise cannot be updated to 3.5.1

### ISSUE THREAD

**Issue by bmorrall** [adamniedzielski/tiddle#9]
It's locked to `~> 3.4.1` due to your gemspec.

Changing the dependency to `~> 3.4` still works as expected, and allows devise to be updated to the latest release.

Pull request in https://github.com/adamniedzielski/tiddle/pull/6

**Comment by adamniedzielski** [comment]
I'm sorry for not responding to your pull request - had a busy week :)

I took a little different approach here. I don't want to allow Devise 3.6.x before testing it, so I locked it as ```< 3.6.0```.

**Comment by bmorrall** [comment]
No problems at all, I wasn't sure if a pull request was enough, or I should've added an Issue first.

I'm just happy I can now update Devise :)
